name: si_pirang
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  table_calendar: ^3.0.0
  http: ^0.13.3
  shared_preferences: ^2.0.12
  flutter_pdfview: ^1.3.2
  image_picker: ^1.0.5
  datetime_picker_formfield: ^2.0.0
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
  - assets/images/aula.jpg
  - assets/images/PONGI.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
